[phases.setup]
nixPkgs = ["nodejs_20", "npm-9_x"]

[phases.install]
cmds = ["cd server && npm ci"]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "cd server && npm start"

